name: Test Python

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  test:
    strategy:
      matrix:
        python: [3.7, 3.10]
    steps:
      # Python & dependency installation
      - uses: actions/checkout@v2
      - name: setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: install requirements
        run: "pip install -r requirements.txt -r dev-requirements.txt"
      - name: docs
        run: (cd docs && make html)
      - name: run tests
        run: "python test_pyopenstates.py"
        env:
          OPENSTATES_API_KEY: ${{ secrets.OPENSTATES_API_KEY }}
      - run: "python setup.py bdist_wheel"
    runs-on: ubuntu-20.04
